//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karakatsiya.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karakatsiya.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h1&gt;Congratulations!&lt;/h1&gt;&lt;p&gt;Your application has been approved. You can now create events on the Karakatsiya platform. Welcome aboard!&lt;/p&gt;.
        /// </summary>
        public static string EMAIL_ORGANIZER_APPROVED_BODY {
            get {
                return ResourceManager.GetString("EMAIL_ORGANIZER_APPROVED_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your organizer application has been approved!.
        /// </summary>
        public static string EMAIL_ORGANIZER_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_ORGANIZER_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h1&gt;Application Rejected&lt;/h1&gt;&lt;p&gt;Unfortunately, your application for organizer status has been rejected.&lt;/p&gt;&lt;p&gt;Reason: {0}&lt;/p&gt;.
        /// </summary>
        public static string EMAIL_ORGANIZER_REJECTED_BODY {
            get {
                return ResourceManager.GetString("EMAIL_ORGANIZER_REJECTED_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Organizer application status.
        /// </summary>
        public static string EMAIL_ORGANIZER_REJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_ORGANIZER_REJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your code is {0}. It is valid for {1} minutes..
        /// </summary>
        public static string EMAIL_VERIFICATION_BODY {
            get {
                return ResourceManager.GetString("EMAIL_VERIFICATION_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation code.
        /// </summary>
        public static string EMAIL_VERIFICATION_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_VERIFICATION_SUBJECT", resourceCulture);
            }
        }
    }
}
